docs: adiciona arquivo de dicionário (#3)
atlantico-academy/fake-news-rating pull request #8
Opened 2022-09-21 22:27 UTC by rafaelxavier-ocn

Criei os dicionários de dados

- `data.csv:` dataframe com os dados
- `discionario.csv`: discionário com o tipo de dado, variável, significado e valores.

2022-09-22 00:50 UTC, omadson requested changes
Inseri algumas correções que precisam ser feitas.

2022-09-22 00:50 UTC, omadson commented on data/external/dicionario.csv
> +text,"Coluna contendo o texto das matérias, sendo cada matéria um dado diferente",Qualitativa nominal,string
Variável `text` é nominal

2022-09-22 00:50 UTC, omadson commented on data/external/dicionario.csv
> +datetime,Coluna contendo a data de publicação das matérias,Quantitativa contínua,datetime
Variável `datetime` é ordinal

2022-09-22 00:50 UTC, omadson commented on data/external/dicionario.csv
> +category,"Coluna contetndo a categoria na qual cada matéria se encaixa (politica, religião, economia, ciencia e tecnologia, celebridades e cotidiano)",Qualitativa ordinal,string
Variável `category` é nominal

2022-09-22 00:50 UTC, omadson commented on data/external/dicionario.csv
> +label,Coluna contendo os rótulos se a notícia é falsa (fake) ou verdadeira (true),Qualitativa ordinal,string
Variável `label` é nominal.

Colocar a lista de possíveis valores

2022-09-22 00:50 UTC, omadson commented on data/external/dicionario.csv
> +site,Coluna contendo o link do site em que a notícia foi publicada,Qualitativa nominal,string
Variável `site` é nominal

2022-09-24 02:58 UTC, rafaelxavier-ocn commented on data/external/dicionario.csv
> +text,"Coluna contendo o texto das matérias, sendo cada matéria um dado diferente",Qualitativa nominal,string
Feito

2022-09-24 02:59 UTC, rafaelxavier-ocn commented on data/external/dicionario.csv
> +category,"Coluna contetndo a categoria na qual cada matéria se encaixa (politica, religião, economia, ciencia e tecnologia, celebridades e cotidiano)",Qualitativa ordinal,string
Feito

2022-09-24 02:59 UTC, rafaelxavier-ocn commented on data/external/dicionario.csv
> +label,Coluna contendo os rótulos se a notícia é falsa (fake) ou verdadeira (true),Qualitativa ordinal,string
Feito

2022-09-24 03:00 UTC, rafaelxavier-ocn commented
Arquivo corrigido.

2022-09-24 03:00 UTC, rafaelxavier-ocn commented on data/external/dicionario.csv
> +site,Coluna contendo o link do site em que a notícia foi publicada,Qualitativa nominal,string
Feito

2022-09-26 14:38 UTC, omadson approved these changes
Tudo certo. Irei aceitar.

2022-09-26 14:38 UTC, merged